#!/usr/bin/env python

from __future__ import print_function
import fileinput
import sys
import urlparse

try:
    import redis
except ImportError:
    print("ERROR: redispipe requires redis-py. `pip install redis` and try again.")
    sys.exit(1)

def get_connection(conn_url):
    url = urlparse.urlparse(conn_url)

    host = url.hostname
    port = url.port

    return redis.StrictRedis(host=host, port=port)

def usage():
    print("Usage: redispipe <redis_url> <list_key>")
    print()
    print("e.g. redispipe redis://localhost:6379 mylog")

def main():
    if len(sys.argv) != 3:
        usage()
        sys.exit(1)

    _, url, listkey = sys.argv

    rc = get_connection(url)

    while 1:
        line = sys.stdin.readline()
        if line == '':
            break
        rc.lpush(listkey, line)

if __name__ == '__main__':
    main()
